const ROLES = {
  ADMINISTRATOR: 'Administrator',
  MANAGER: 'Manager',
  DATA_ENTRY: 'Data Entry',
  CONSULTANT: 'Consultant',
};

const ALL_ROLES = Object.values(ROLES);

const HARDWARE_WRITE_ROLES = [
  ROLES.ADMINISTRATOR,
  ROLES.MANAGER,
  ROLES.DATA_ENTRY,
];

/** Roles that may submit catalogue change requests. */
const APPROVAL_SUBMIT_ROLES = HARDWARE_WRITE_ROLES;

/** Roles that may approve or reject change requests. */
const APPROVAL_REVIEW_ROLES = [
  ROLES.ADMINISTRATOR,
  ROLES.MANAGER,
];

const ENTITY_TYPES = {
  HARDWARE: 'HARDWARE',
  USER: 'USER',
};

const ALL_ENTITY_TYPES = Object.values(ENTITY_TYPES);

/** Audit actions for User Management (immutable audit trail). */
const USER_AUDIT_ACTIONS = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  PASSWORD_RESET: 'PASSWORD_RESET',
};

const ALL_USER_AUDIT_ACTIONS = Object.values(USER_AUDIT_ACTIONS);

const CHANGE_REQUEST_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
};

const ALL_CHANGE_REQUEST_ACTIONS = Object.values(CHANGE_REQUEST_ACTIONS);

const CHANGE_REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const ALL_CHANGE_REQUEST_STATUSES = Object.values(CHANGE_REQUEST_STATUS);

const SYNC_STATUS = {
  WAITING: 'Waiting',
  NO_INTEGRATION: 'No Integration',
  PENDING: 'Pending',
  READY: 'Ready',
};

const ALL_SYNC_STATUSES = Object.values(SYNC_STATUS);

const AUDIT_DECISIONS = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const ALL_AUDIT_DECISIONS = Object.values(AUDIT_DECISIONS);

const NOTIFICATION_TYPES = {
  APPROVAL_SUBMITTED: 'APPROVAL_SUBMITTED',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
};

const ALL_NOTIFICATION_TYPES = Object.values(NOTIFICATION_TYPES);

const CHANGE_REQUEST_SORT_FIELDS = [
  'submittedAt',
  'status',
  'action',
  'createdAt',
  'updatedAt',
];

const AUDIT_SORT_FIELDS = [
  'createdAt',
  'decision',
  'stockCode',
  'action',
];

const PRICING_BASIS = {
  AGREED: 'Agreed',
  RETAIL: 'Retail',
};

const ALL_PRICING_BASIS = Object.values(PRICING_BASIS);

const HARDWARE_SORT_FIELDS = [
  'stockCode',
  'groupCode',
  'description',
  'createdAt',
  'updatedAt',
];

const BOARDS_SORT_FIELDS = [
  'boardCode',
  'description',
  'supplier',
  'range',
  'colour',
  'finish',
  'boardType',
  'createdAt',
  'updatedAt',
];

const USER_SORT_FIELDS = [
  'name',
  'email',
  'role',
  'createdAt',
  'lastLogin',
];

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

module.exports = {
  ROLES,
  ALL_ROLES,
  HARDWARE_WRITE_ROLES,
  APPROVAL_SUBMIT_ROLES,
  APPROVAL_REVIEW_ROLES,
  ENTITY_TYPES,
  ALL_ENTITY_TYPES,
  USER_AUDIT_ACTIONS,
  ALL_USER_AUDIT_ACTIONS,
  CHANGE_REQUEST_ACTIONS,
  ALL_CHANGE_REQUEST_ACTIONS,
  CHANGE_REQUEST_STATUS,
  ALL_CHANGE_REQUEST_STATUSES,
  SYNC_STATUS,
  ALL_SYNC_STATUSES,
  AUDIT_DECISIONS,
  ALL_AUDIT_DECISIONS,
  NOTIFICATION_TYPES,
  ALL_NOTIFICATION_TYPES,
  CHANGE_REQUEST_SORT_FIELDS,
  AUDIT_SORT_FIELDS,
  PRICING_BASIS,
  ALL_PRICING_BASIS,
  HARDWARE_SORT_FIELDS,
  BOARDS_SORT_FIELDS,
  USER_SORT_FIELDS,
  PAGINATION,
  HTTP_STATUS,
};
